// Class automatically generated by Dev-C++ New Class wizard

#include "casilla.h" // class's header file
using namespace std;

// class constructor
Casilla::Casilla(int fila, int col)
{
    num = 9*fila + col;
	valor = 0;
	lleno = false;
	this->fila = fila;
    this->col = col;
    cuadro = 3*int(fila/3) + int(col/3);
    for (int i=1;i<=9;i++) valores_posibles.push_back(i);
}


// class destructor
Casilla::~Casilla()
{
	// insert your code here
}

int Casilla::num_valores_posibles(void)
{
    return (valores_posibles.size());
}
