// Class automatically generated by Dev-C++ New Class wizard

#ifndef CASILLA_H
#define CASILLA_H

#include <vector>
using namespace std;

/*
 * Informacion sobre una casilla
 */
class Casilla
{
	public:
        int num;
        int valor;
        bool lleno;
        int fila;
        int col;
        int cuadro;
        vector<int> valores_posibles;
		// class constructor
		Casilla(int,int);
		Casilla();
		// class destructor
		~Casilla();
		int num_valores_posibles(void);
};

#endif // CASILLA_H
